MagicWebservices/MagicWebservices/Controllers/MortisController.cs
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web.Http.Cors;
using System.Web.Mvc;
using MagicWebservices.Controllers.Mortis;
using MagicWebservices.Controllers.Mortis.Database;
using MagicWebservices.Controllers.Mortis.NewpointsShopManager;
using MagicWebservices.Controllers.Processes;

namespace MagicWebservices.Controllers
{
    [EnableCors(origins: "*", headers: "*", methods: "*")]
    public class MortisController : Controller
    {
        #region Fields
        private static ProcessesGroup fiveMinutesProcesses;
        private static ProcessesGroup twentyFourHoursProcesses;
        #endregion
        #region Methods

        [System.Web.Http.HttpGet]
        public JsonResult GetAllUsers()
        {
            List<UserNameId> userNameIds = new List<UserNameId>();
            using (var database = new MortisModelContainer())
            {
                userNameIds.AddRange(database.mybb_users.Select(u => new UserNameId
                {
                    UserId = u.uid,
                    Username = u.username
                }).OrderBy(u => u.Username));
            }
            Response.AppendHeader("Access-Control-Allow-Origin", "*");
            return new JsonResult
            {
                ContentEncoding = Encoding.UTF8,
                Data = userNameIds,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        private class UserNameId
        {
            public string Username { get; set; }
            public long UserId { get; set; }
        }

        [System.Web.Http.HttpGet]
        public ActionResult RebuildSpells()
        {
            return View("~/Views/Mortis/ShowReport.cshtml", MortisTasks.OnDemand.RebuildSpells());
        }

        [System.Web.Http.HttpGet]
        public ActionResult ChangePostAuthor(long postId, int newUserId)
        {
            return View("~/Views/Mortis/ShowReport.cshtml", MortisTasks.OnDemand.ChangePostAuthor(postId, newUserId));
        }

        private void InitializeFiveMinutesProcessesGroup()
        {
            fiveMinutesProcesses = new ProcessesGroup("FiveMinutesProcesses")
            {
                new SingleProcess(MortisTasks.FiveMinutes.UpdateProfileShopItems),
                new SingleProcess(MortisTasks.FiveMinutes.UpdateDepositLinks),
                new SingleProcess(MortisTasks.FiveMinutes.UpdateOwlMailLinks),
                new SingleProcess(MortisTasks.FiveMinutes.UpdateDiaryLinks)
            };
        }

        private void InitializeTwentyFourHoursProcessesGroup()
        {
            twentyFourHoursProcesses = new ProcessesGroup("TwentyFourHoursProcesses")
            {
                new SingleProcess(MortisTasks.TwentyFourHours.DeletePostsOlderThanTwoWeeksInThread)
            };
        }


        [System.Web.Http.HttpGet]
        public ActionResult ExecuteFiveMinutesProcesses()
        {
            if (fiveMinutesProcesses == null)
                InitializeFiveMinutesProcessesGroup();
            fiveMinutesProcesses.ExecuteAll();
            return RedirectToAction("FiveMinutesProcessesReport");
        }

        [System.Web.Http.HttpGet]
        public ActionResult ExecuteFiveMinutesProcessesApi()
        {
            if (fiveMinutesProcesses == null)
                InitializeFiveMinutesProcessesGroup();
            return View("~/Views/Mortis/ProcessesReport.cshtml", fiveMinutesProcesses.ExecuteAll());
        }

        [System.Web.Http.HttpGet]
        public ActionResult FiveMinutesProcessesReport()
        {
            if (fiveMinutesProcesses == null)
                InitializeFiveMinutesProcessesGroup();
            return View("~/Views/Mortis/ProcessesReport.cshtml", fiveMinutesProcesses.GetCurrentResults());
        }

        [System.Web.Http.HttpGet]
        public ActionResult ExecuteTwentyFourHoursProcesses()
        {
            if (twentyFourHoursProcesses == null)
                InitializeTwentyFourHoursProcessesGroup();
            twentyFourHoursProcesses.ExecuteAll();
            return RedirectToAction("TwentyFourHoursProcessesReport");
        }

        [System.Web.Http.HttpGet]
        public ActionResult ExecuteTwentyFourHoursProcessesApi()
        {
            if (twentyFourHoursProcesses == null)
                InitializeTwentyFourHoursProcessesGroup();
            return View("~/Views/Mortis/ProcessesReport.cshtml", twentyFourHoursProcesses.ExecuteAll());
        }

        [System.Web.Http.HttpGet]
        public ActionResult TwentyFourHoursProcessesReport()
        {
            if (twentyFourHoursProcesses == null)
                InitializeTwentyFourHoursProcessesGroup();
            return View("~/Views/Mortis/ProcessesReport.cshtml", twentyFourHoursProcesses.GetCurrentResults());
        }

        [System.Web.Http.HttpGet]
        public ActionResult NewpointsShopManager(string loginKey)
        {
            NewpointsShopManagerData data = NewpointsShopManagerData.GetNewpointsShopManagerDataForToken(loginKey);
            return data.CurrentUserPermissions == NewpointsManagerPermissions.None 
                ? View("~/Views/Mortis/NewpointsShopManagerNoPermissions.cshtml", data) 
                : View("~/Views/Mortis/NewpointsShopManager.cshtml", data);
        }

        [System.Web.Http.HttpPost]
        public ActionResult ChangePointsValue(NewpointsShopManagerData data)
        {
            data.PointsChange.ApplyPointsChange();
            return RedirectToAction("NewpointsShopManager", new { loginKey = data.CurrentUserUidAndLoginKey });
        }

        [System.Web.Http.HttpPost]
        public ActionResult ChangeSpells(NewpointsShopManagerData data)
        {
            data.SpellsChange.ApplySpellsChange();
            return RedirectToAction("NewpointsShopManager", new { loginKey = data.CurrentUserUidAndLoginKey });
        }
        #endregion
    }
}

MagicWebservices/MagicWebservices/Views/Mortis/NewpointsShopManager.cshtml
@using MagicWebservices.Controllers.Mortis.NewpointsShopManager
@using System.Web.Helpers
@model NewpointsShopManagerData
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Newpoints Shop Manager</title>
    <!-- start: headerinclude -->
    <link rel="alternate" type="application/rss+xml" title="Najnowsze wątki (RSS 2.0)" href="https://mortis.org.pl/syndication.php" />
    <link rel="alternate" type="application/atom+xml" title="Najnowsze wątki (Atom 1.0)" href="https://mortis.org.pl/syndication.php?type=atom1.0" />
    <link href='//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Bigelow+Rules|Elsie|Marcellus|Parisienne|Playfair+Display|Roboto&amp;subset=latin-ext" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,200italic,400italic,600italic' rel='stylesheet' type='text/css'>
    <meta https-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta https-equiv="Content-Script-Type" content="text/javascript" />
    <script type="text/javascript" src="https://mortis.org.pl/jscripts/jquery.js?ver=1800"></script>
    <script type="text/javascript" src="https://mortis.org.pl/jscripts/jquery.plugins.min.js?ver=1800"></script>
    <script type="text/javascript" src="https://mortis.org.pl/jscripts/general.js?ver=1800"></script>

    <link type="text/css" rel="stylesheet" href="https://mortis.org.pl/cache/themes/theme8/avatarep.css" />
    <link type="text/css" rel="stylesheet" href="https://mortis.org.pl/cache/themes/theme8/css3.css" />
    <link type="text/css" rel="stylesheet" href="https://mortis.org.pl/cache/themes/theme8/global.css" />
    <link type="text/css" rel="stylesheet" href="https://mortis.org.pl/cache/themes/theme8/contactdropdown.css" />
    <link type="text/css" rel="stylesheet" href="https://mortis.org.pl/cache/themes/theme8/dd.css" />
    <link type="text/css" rel="stylesheet" href="https://mortis.org.pl/cache/themes/theme8/extra.css" />
    <link type="text/css" rel="stylesheet" href="https://mortis.org.pl/cache/themes/theme8/tipsy.css" />
    <link type="text/css" rel="stylesheet" href="https://mortis.org.pl/cache/themes/theme8/profiles.css" />
    <link type="text/css" rel="stylesheet" href="https://mortis.org.pl/cache/themes/theme8/inferno.css" />
    <link type="text/css" rel="stylesheet" href="https://mortis.org.pl/cache/themes/theme8/itemHeader.css" />
    <link type="text/css" rel="stylesheet" href="https://mortis.org.pl/cache/themes/theme8/ImageScale.css" />
    <link type="text/css" rel="stylesheet" href="https://mortis.org.pl/cache/themes/theme8/NPCStyle.css" />
    <link type="text/css" rel="stylesheet" href="https://mortis.org.pl/cache/themes/theme8/AnnoucmentTabs.css" />
    <link type="text/css" rel="stylesheet" href="https://mortis.org.pl/cache/themes/theme8/ManagerStyles.css" />

    <script type="text/javascript">
<!--
	lang.unknown_error = "Wystąpił nieznany błąd.";

	lang.select2_match = "Dostępny jest jeden wynik. Wciśnij enter, aby go wybrać.";
	lang.select2_matches = "Dostępnych wyników: {1}. Użyj strzałek w dół i w górę, aby nawigować.";
	lang.select2_nomatches = "Nic nie znaleziono";
	lang.select2_inputtooshort_single = "Wpisz co najmniej jeden znak";
	lang.select2_inputtooshort_plural = "Wpisz {1} lub więcej znaków";
	lang.select2_inputtoolong_single = "Usuń jeden znak";
	lang.select2_inputtoolong_plural = "Usuń {1} znaki/znaków";
	lang.select2_selectiontoobig_single = "Możesz wybrać tylko jednen wynik";
	lang.select2_selectiontoobig_plural = "Możesz wybrać tylko {1} wyniki/wyników";
	lang.select2_loadmore = "Wczytywanie większej ilości wyników";
	lang.select2_searching = "Wyszukiwanie";

	var cookieDomain = ".mortis.org.pl";
	var cookiePath = "/";
	var cookiePrefix = "";
	var deleteevent_confirm = "Czy na pewno chcesz usunąć to wydarzenie?";
	var removeattach_confirm = "Czy na pewno chcesz usunąć zaznaczone załączniki?";
	var loading_text = 'Wczytywanie<br />Proszę czekać...';
	var saving_changes = 'Zapisywanie zmian...';
	var use_xmlhttpsrequest = "1";
	var my_post_key = "ec63e171c490f8392732845007dfa011";
	var rootpath = "https://mortis.org.pl";
	var imagepath = "https://mortis.org.pl/images/vienna/";
  	var yes_confirm = "Tak";
	var no_confirm = "Nie";
	var MyBBEditor = null;
	var spinner_image = "https://mortis.org.pl/images/vienna//spinner.gif";
	var spinner = "<img src='" + spinner_image +"' alt='' />";
// -->
    </script>
    <!-- end: headerinclude -->
<style>
    .webgrid-table
    {
        border: solid 1px #777777;
        margin: auto;
        text-align: center;
    }
    .webgrid-table td, th
    {
        border: 1px solid #777777;
        padding: 3px 7px 2px;
    }
</style>
</head>
<body style="background: none; width: 100%;">
    @{
        var pointsHeaderAdd = $"{(Model.CurrentUserPermissions.HasFlag(NewpointsManagerPermissions.AddPoints) ? "Dodaj" : "")}";
        var pointsHeaderSubtract = $"{(Model.CurrentUserPermissions.HasFlag(NewpointsManagerPermissions.SubtractPoints) ? "Odejmij" : "")}";
        var pointsHeaderAddOrSubtract = $"{pointsHeaderAdd}/{pointsHeaderSubtract}".Trim('/');
        var pointsHeader = $"{(!string.IsNullOrWhiteSpace(pointsHeaderAddOrSubtract) ? pointsHeaderAddOrSubtract : "")} punkty";
        var pointsDivStyle = Model.CurrentUserPermissions.HasFlag(NewpointsManagerPermissions.AddPoints) || Model.CurrentUserPermissions.HasFlag(NewpointsManagerPermissions.SubtractPoints)
            ? "" : "display:none;";
        var pointsInputAttribute = "";
        if (!(Model.CurrentUserPermissions.HasFlag(NewpointsManagerPermissions.AddPoints) && Model.CurrentUserPermissions.HasFlag(NewpointsManagerPermissions.SubtractPoints))
            && (pointsDivStyle == ""))
        {
            pointsInputAttribute = Model.CurrentUserPermissions.HasFlag(NewpointsManagerPermissions.AddPoints) ? "min=1" : "";
            pointsInputAttribute += Model.CurrentUserPermissions.HasFlag(NewpointsManagerPermissions.SubtractPoints) ? "max=-1" : "";
        }
    }
    <div style="width: 100%; margin: 30px auto;@pointsDivStyle">
        <span class="thead"><strong>@pointsHeader</strong></span>
        @using (Html.BeginForm("ChangePointsValue", "Mortis", FormMethod.Post, new { @style = "margin-top:15px;" }))
        {
            <input type="hidden" name="PointsChange.ManagerUid" value="@Model.CurrentUser.uid" />
            @Html.HiddenFor(model => model.CurrentUserUidAndLoginKey)
            <input type="number" name="PointsChange.PointsChange" value="0" class="textbox" @pointsInputAttribute />
            @Html.DropDownListFor(model => model.PointsChange.Uid, new SelectList(Model.UserList, "uid", "username"), "wybierz użytkownika")
            @Html.TextBoxFor(model => model.PointsChange.Reason, new { @placeholder = "przyczyna zmiany", @class="textbox"}); 
            <input type="submit" value="Zmień punkty" class="button" />
        }
    </div>
    @{
        var spellsHeaderAdd = $"{(Model.CurrentUserPermissions.HasFlag(NewpointsManagerPermissions.AddSpells) ? "Dodaj" : "")}";
        var spellsHeaderSubtract = $"{(Model.CurrentUserPermissions.HasFlag(NewpointsManagerPermissions.SubtractSpells) ? "Usuń" : "")}";
        var spellsHeaderAddOrSubtract = $"{spellsHeaderAdd}/{spellsHeaderSubtract}".Trim('/');
        var spellsHeader = $"{(!string.IsNullOrWhiteSpace(spellsHeaderAddOrSubtract) ? spellsHeaderAddOrSubtract : "")} zaklęcia";
        var spellDivStyle = Model.CurrentUserPermissions.HasFlag(NewpointsManagerPermissions.AddSpells) || Model.CurrentUserPermissions.HasFlag(NewpointsManagerPermissions.SubtractSpells)
            ? "" : "display:none;";
        Model.SpellsChange = new NewpointsShopSpellsChange() { Add = Model.CurrentUserPermissions.HasFlag(NewpointsManagerPermissions.AddSpells) };

    }
    <div style="@spellDivStyle">
        <span><strong class="thead">@spellsHeader</strong></span>
        @using (Html.BeginForm("ChangeSpells", "Mortis", FormMethod.Post, new { @style = "margin-top:15px;" }))
        {
            @Html.HiddenFor(model => model.CurrentUserUidAndLoginKey)
            <input type="hidden" name="SpellsChange.ManagerUid" value="@Model.CurrentUser.uid" />
            @Html.ListBoxFor(x => x.SpellsChange.SpellsIids, new SelectList(Model.SpellList, "iid", "name"), new { @style = "height:200px" })
            @Html.DropDownListFor(model => model.SpellsChange.Uid, new SelectList(Model.UserList, "uid", "username"), "wybierz użytkownika")
            if (Model.CurrentUserPermissions.HasFlag(NewpointsManagerPermissions.AddSpells))
            {
                @Html.RadioButtonFor(x => x.SpellsChange.Add, true)
                @Html.Label("Dodaj")
            }
            if (Model.CurrentUserPermissions.HasFlag(NewpointsManagerPermissions.SubtractSpells))
            {
                @Html.RadioButtonFor(x => x.SpellsChange.Add, false)
                @Html.Label("Usuń")
            }
            @Html.TextBoxFor(model => model.SpellsChange.Reason, new { @placeholder = "przyczyna zmiany", @class = "textbox" });
            <input type="submit" value="Zmień zaklęcia" class="button" />
        }
        @{
            var logGrid = new WebGrid(Model.LogInfo,
                columnNames: new[] { "ManagerUsername", "What", "Username", "When", "Why" });
            var gridDivStyle = Model.CurrentUserPermissions.HasFlag(NewpointsManagerPermissions.SeeLog) ? "" : "display:none;";
        }
    </div>
    <div style="width: 100%; margin: 30px auto; text-align: center; @gridDivStyle">
        @logGrid.GetHtml(columns: logGrid.Columns(
            logGrid.Column(columnName: "ManagerUsername", header: "Kto"),
            logGrid.Column(columnName: "What", header: "Co"),
            logGrid.Column(columnName: "Username", header: "Komu"),
            logGrid.Column(columnName: "When", header: "Kiedy"),
            logGrid.Column(columnName: "Why", header: "Dlaczego")),
            headerStyle: "thead",
            tableStyle: "webgrid-table")
    </div>
</body>



</html>

MagicWebservices/MagicWebservices/Views/Mortis/NewpointsShopManagerNoPermissions.cshtml
@model MagicWebservices.Controllers.Mortis.NewpointsShopManager.NewpointsShopManagerData
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Newpoints Shop Manager</title>
</head>
<body style="background:none">
<div>
    <h2 style="text-align: center">@Model.CurrentUser.username nie ma tu wstępu!</h2>
    <h2 style="text-align: center">Nawet Alohomora ci tu nie pomoże!</h2>
</div>
</body>
</html>

MagicWebservices/MagicWebservices/Views/Mortis/ProcessesReport.cshtml
@model MagicWebservices.Controllers.Processes.ProcessGroupResult

@{
    ViewBag.Title = @Model.ProcessGroupName;
    Layout = null;
}

<h2>ProcessesReport</h2>

<div>
@Html.Raw(Model.GroupResultMessage().Replace("\n", "<br/>"))
</div>

MagicWebservices/MagicWebservices/Views/Mortis/ShowReport.cshtml
@model MagicWebservices.Models.Report

@{
    ViewBag.Title = @Model.Name;
    Layout = null;
}

<h2>ProcessesReport</h2>

<div>
@Html.Raw(HttpUtility.HtmlEncode(Model.Data)?.Replace("\n", "<br/>"))
</div>